/** Exact demo content from reference/amazon-sc/dashboard.png.png */
export const SC_DASHBOARD = {
  greeting: "Good afternoon",
  accountHealth: "Healthy",
  actionsCount: 0,
  globalSnapshot: {
    sales: {
      value: "₹12,379.38",
      sub: "Today so far",
      sparkline: [1, 2, 2, 3, 4, 3, 5, 6, 5, 7, 8, 10, 9, 12, 14],
    },
    openOrders: {
      value: "8",
      sub: "Total Count",
      lines: [
        { label: "FBM Unshipped", count: 1 },
        { label: "FBM Pending", count: 0 },
        { label: "FBA Pending", count: 0 },
      ],
    },
    buyerMessages: { value: "0", sub: "Cases requiring attention" },
    featuredOffer: { value: "100%", sub: "2 days ago" },
    globalPromotions: { value: "₹37,326.94", sub: "Last 7 days" },
    adSales: { value: "₹5,306.46", sub: "Today so far" },
    adImpressions: { value: "16,700", sub: "Today so far" },
    sellerFeedback: { value: "4.8", sub: "Past Year (2004)", rating: 4.8 },
    payments: { value: "₹88,516.64", sub: "Total Balance" },
  },
  forums: [
    {
      id: "1",
      title: "Unlock Brand Analytics insights with Brand Registry",
      date: "Feb 27",
      views: 155,
      comments: 0,
    },
    {
      id: "2",
      title: "Late dispatch cancellation rate",
      date: "Feb 26",
      views: 89,
      comments: 2,
    },
    {
      id: "3",
      title: "Check your Q1 STEP level and eligibility",
      date: "Feb 24",
      views: 214,
      comments: 5,
    },
  ],
  news: [
    {
      id: "1",
      title: "Changes to review sharing policy",
      body: "Starting March 15, Amazon will update how product reviews are shared across regional marketplaces.",
      date: "26-Feb-2026",
    },
    {
      id: "2",
      title: "Track Amazon Business customer return requests",
      body: "New tools are available to help you manage and respond to Amazon Business return requests.",
      date: "24-Feb-2026",
    },
    {
      id: "3",
      title: "Check your Q1 STEP level and eligibility",
      body: "Review your STEP tier status and eligibility requirements for the upcoming quarter.",
      date: "22-Feb-2026",
    },
  ],
  products: [
    {
      id: "1",
      title: "TELGO Unisex Laptop Travel Back...",
      asin: "B089N6F2C9",
      sku: "TELGO-SKY-001",
      seed: "telgo-backpack-blue",
      inventory: "10 FBM",
      price: "₹999.00",
    },
    {
      id: "2",
      title: "TELGO Unisex Laptop Travel Back...",
      asin: "B089N6F2C9",
      sku: "TELGO-NVY-001",
      seed: "telgo-backpack-navy",
      inventory: "10 FBM",
      price: "₹999.00",
    },
    {
      id: "3",
      title: "TELGO Unisex Laptop Travel Back...",
      asin: "B089N6F2C9",
      sku: "TELGO-BLK-001",
      seed: "telgo-backpack-black",
      inventory: "100 FBM",
      price: "₹649.00",
    },
    {
      id: "4",
      title: "TELGO Unisex Laptop Travel Back...",
      asin: "B089N6F2C9",
      sku: "TELGO-GRY-001",
      seed: "telgo-backpack-grey",
      inventory: "100 FBM",
      price: "₹649.00",
    },
    {
      id: "5",
      title: "TELGO Unisex Laptop Travel Back...",
      asin: "B089N6F2C9",
      sku: "TELGO-RED-001",
      seed: "telgo-backpack-red",
      inventory: "10 FBM",
      price: "₹999.00",
    },
  ],
} as const;
