import { generateDailyTrend } from "@/lib/demo/dashboard/helpers";
import type { DashboardDataMap } from "@/types/dashboard";

export const dashboardDataByCategory: DashboardDataMap = {
  "home-decor": {
    lastUpdated: "Today at 9:42 AM EST",
    kpis: {
      todaysSales: 1_842.5,
      todaysSalesChange: 8.3,
      totalOrders: 1_247,
      totalOrdersChange: 5.1,
      totalRevenue: 48_230.17,
      totalRevenueChange: 11.2,
      pendingOrders: 34,
      returnOrders: 18,
      conversionRate: 3.6,
      conversionRateChange: 0.4,
    },
    dailyTrend: generateDailyTrend(101, 1420, 3820, 38, 1.2),
    revenueBreakdown: [
      { name: "Wall Art & Mirrors", value: 14_520, color: "#FF9900" },
      { name: "Textiles & Pillows", value: 12_890, color: "#146EB4" },
      { name: "Lighting", value: 9_340, color: "#067D62" },
      { name: "Planters & Vases", value: 7_680, color: "#CC0C39" },
      { name: "Seasonal Decor", value: 3_800, color: "#232F3E" },
    ],
    categoryPerformance: [
      { name: "Living Room", sales: 18_420, fill: "#FF9900" },
      { name: "Bedroom", sales: 12_650, fill: "#146EB4" },
      { name: "Bathroom", sales: 8_940, fill: "#067D62" },
      { name: "Outdoor", sales: 5_220, fill: "#CC0C39" },
      { name: "Office", sales: 3_000, fill: "#565959" },
    ],
    inventoryAlerts: [
      { id: "hd-a1", product: "Ceramic Table Lamp — Sage", sku: "NNH-LMP-042", message: "Only 3 units left at FBA warehouse PHX7", severity: "critical" },
      { id: "hd-a2", product: "Macramé Wall Hanging 36in", sku: "NNH-MCR-118", message: "Reorder point reached — supplier lead time 12 days", severity: "warning" },
      { id: "hd-a3", product: "Bamboo Floating Shelf Set", sku: "NNH-SHF-207", message: "Inbound shipment delayed by 2 days", severity: "info" },
    ],
    lowStock: [
      { id: "hd-l1", product: "Linen Throw Pillow — Oatmeal", sku: "NNH-PLW-033", stock: 8, threshold: 25, imageSeed: "hd-linen-pillow" },
      { id: "hd-l2", product: "Scented Candle Trio Gift Set", sku: "NNH-CND-091", stock: 12, threshold: 30, imageSeed: "hd-candle-trio" },
      { id: "hd-l3", product: "Rattan Storage Basket Large", sku: "NNH-BSK-156", stock: 5, threshold: 20, imageSeed: "hd-rattan-basket" },
      { id: "hd-l4", product: "Minimalist Clock — Walnut", sku: "NNH-CLK-044", stock: 9, threshold: 22, imageSeed: "hd-walnut-clock" },
    ],
    recentOrders: [
      { id: "hd-o1", orderNumber: "114-8829103", customer: "Sarah M.", product: "Velvet Accent Chair Cover", amount: 47.99, status: "shipped", timeAgo: "12 min ago", imageSeed: "hd-chair-cover" },
      { id: "hd-o2", orderNumber: "114-8829044", customer: "James K.", product: "Ceramic Vase Set of 3", amount: 62.5, status: "pending", timeAgo: "28 min ago", imageSeed: "hd-vase-set" },
      { id: "hd-o3", orderNumber: "114-8828971", customer: "Emily R.", product: "Woven Area Rug 5x7", amount: 129.0, status: "delivered", timeAgo: "1 hr ago", imageSeed: "hd-woven-rug" },
      { id: "hd-o4", orderNumber: "114-8828890", customer: "David L.", product: "LED String Lights 50ft", amount: 24.99, status: "shipped", timeAgo: "2 hr ago", imageSeed: "hd-string-lights" },
      { id: "hd-o5", orderNumber: "114-8828755", customer: "Anna P.", product: "Marble Coaster Set", amount: 19.95, status: "returned", timeAgo: "3 hr ago", imageSeed: "hd-marble-coaster" },
    ],
    notifications: [
      { id: "hd-n1", title: "Buy Box won", message: "Bamboo Floating Shelf Set regained the Buy Box on Amazon.com", timeAgo: "18 min ago", type: "system" },
      { id: "hd-n2", title: "FBA restock reminder", message: "12 SKUs below recommended restock quantity", timeAgo: "45 min ago", type: "inventory" },
      { id: "hd-n3", title: "Payout scheduled", message: "$4,218.44 disbursement scheduled for Feb 4", timeAgo: "2 hr ago", type: "payment" },
      { id: "hd-n4", title: "New review", message: "5-star review on Linen Throw Pillow — Oatmeal", timeAgo: "4 hr ago", type: "system" },
    ],
    activityTimeline: [
      { id: "hd-t1", title: "Order shipped", description: "114-8829103 — Velvet Accent Chair Cover to Phoenix, AZ", timeAgo: "12 min ago", type: "order" },
      { id: "hd-t2", title: "Low stock alert", description: "Rattan Storage Basket Large dropped to 5 units", timeAgo: "35 min ago", type: "inventory" },
      { id: "hd-t3", title: "Listing updated", description: "Ceramic Table Lamp — Sage price adjusted to $54.99", timeAgo: "1 hr ago", type: "listing" },
      { id: "hd-t4", title: "Return initiated", description: "114-8828755 — Marble Coaster Set return request approved", timeAgo: "3 hr ago", type: "return" },
      { id: "hd-t5", title: "Inbound received", description: "Shipment FBA18XKP2 — 240 units checked in at PHX7", timeAgo: "5 hr ago", type: "inventory" },
      { id: "hd-t6", title: "Payment processed", description: "Standard disbursement of $4,218.44 initiated", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  fashion: {
    lastUpdated: "Today at 10:15 AM EST",
    kpis: {
      todaysSales: 4_218.75,
      todaysSalesChange: 12.6,
      totalOrders: 3_412,
      totalOrdersChange: 9.8,
      totalRevenue: 127_840.52,
      totalRevenueChange: 14.3,
      pendingOrders: 112,
      returnOrders: 89,
      conversionRate: 2.9,
      conversionRateChange: -0.2,
    },
    dailyTrend: generateDailyTrend(202, 3680, 9200, 98, 2.1),
    revenueBreakdown: [
      { name: "Women's Apparel", value: 52_400, color: "#CC0C39" },
      { name: "Men's Apparel", value: 38_920, color: "#232F3E" },
      { name: "Accessories", value: 18_650, color: "#FF9900" },
      { name: "Footwear", value: 12_470, color: "#146EB4" },
      { name: "Activewear", value: 5_400, color: "#067D62" },
    ],
    categoryPerformance: [
      { name: "Dresses", sales: 34_200, fill: "#CC0C39" },
      { name: "Denim", sales: 28_900, fill: "#232F3E" },
      { name: "Tops & Tees", sales: 24_150, fill: "#FF9900" },
      { name: "Outerwear", sales: 19_800, fill: "#146EB4" },
      { name: "Accessories", sales: 20_790, fill: "#067D62" },
    ],
    inventoryAlerts: [
      { id: "fn-a1", product: "Slim Fit Chino — Navy 32x32", sku: "UTC-CHN-412", message: "Size run broken — only 32x32 remaining", severity: "critical" },
      { id: "fn-a2", product: "Merino Wool Crew Sweater", sku: "UTC-SWT-089", message: "High return rate (14%) flagged for quality review", severity: "warning" },
      { id: "fn-a3", product: "Leather Belt — Cognac", sku: "UTC-BLT-033", message: "Seasonal demand spike — consider restock", severity: "info" },
    ],
    lowStock: [
      { id: "fn-l1", product: "High-Rise Skinny Jean — Black 28", sku: "UTC-JEN-201", stock: 6, threshold: 40, imageSeed: "fn-skinny-jean" },
      { id: "fn-l2", product: "Cotton Oxford Shirt — White M", sku: "UTC-SHT-118", stock: 11, threshold: 35, imageSeed: "fn-oxford-shirt" },
      { id: "fn-l3", product: "Crossbody Bag — Tan", sku: "UTC-BAG-067", stock: 4, threshold: 18, imageSeed: "fn-crossbody-bag" },
      { id: "fn-l4", product: "Running Sneaker — Grey 10", sku: "UTC-SNK-302", stock: 7, threshold: 28, imageSeed: "fn-running-sneaker" },
    ],
    recentOrders: [
      { id: "fn-o1", orderNumber: "112-4412098", customer: "Olivia H.", product: "Floral Midi Dress — S", amount: 58.0, status: "shipped", timeAgo: "8 min ago", imageSeed: "fn-floral-dress" },
      { id: "fn-o2", orderNumber: "112-4411987", customer: "Marcus T.", product: "Slim Fit Chino — Navy", amount: 44.99, status: "pending", timeAgo: "22 min ago", imageSeed: "fn-chino-navy" },
      { id: "fn-o3", orderNumber: "112-4411876", customer: "Priya S.", product: "Cashmere Blend Scarf", amount: 39.95, status: "delivered", timeAgo: "45 min ago", imageSeed: "fn-cashmere-scarf" },
      { id: "fn-o4", orderNumber: "112-4411765", customer: "Chris W.", product: "Bomber Jacket — Olive L", amount: 89.0, status: "shipped", timeAgo: "1 hr ago", imageSeed: "fn-bomber-jacket" },
      { id: "fn-o5", orderNumber: "112-4411654", customer: "Nina B.", product: "Silk Blouse — Ivory M", amount: 52.5, status: "returned", timeAgo: "2 hr ago", imageSeed: "fn-silk-blouse" },
    ],
    notifications: [
      { id: "fn-n1", title: "Size alert", message: "Slim Fit Chino — Navy running low on 32x30 and 34x32", timeAgo: "10 min ago", type: "inventory" },
      { id: "fn-n2", title: "Flash sale performance", message: "Weekend flash sale drove 847 orders in 48 hours", timeAgo: "1 hr ago", type: "order" },
      { id: "fn-n3", title: "Brand Registry", message: "Urban Thread Co. brand protection report available", timeAgo: "3 hr ago", type: "system" },
      { id: "fn-n4", title: "Refund processed", message: "$52.50 refund for order 112-4411654 completed", timeAgo: "5 hr ago", type: "payment" },
    ],
    activityTimeline: [
      { id: "fn-t1", title: "Bulk order received", description: "112-4412098 — 3 items in multi-unit fashion order", timeAgo: "8 min ago", type: "order" },
      { id: "fn-t2", title: "Return approved", description: "Silk Blouse — Ivory M size exchange approved", timeAgo: "2 hr ago", type: "return" },
      { id: "fn-t3", title: "New variation added", description: "Merino Wool Sweater — Burgundy colorway live", timeAgo: "4 hr ago", type: "listing" },
      { id: "fn-t4", title: "Inventory adjustment", description: "Crossbody Bag — Tan count corrected at EWR4", timeAgo: "6 hr ago", type: "inventory" },
      { id: "fn-t5", title: "Advertising report", description: "Sponsored Products ACOS improved to 18.2%", timeAgo: "Yesterday", type: "listing" },
      { id: "fn-t6", title: "Payout completed", description: "$11,842.19 deposited to account ending 4892", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  kitchen: {
    lastUpdated: "Today at 8:58 AM EST",
    kpis: {
      todaysSales: 2_156.3,
      todaysSalesChange: 6.7,
      totalOrders: 2_156,
      totalOrdersChange: 4.2,
      totalRevenue: 73_615.89,
      totalRevenueChange: 8.9,
      pendingOrders: 58,
      returnOrders: 31,
      conversionRate: 4.1,
      conversionRateChange: 0.6,
    },
    dailyTrend: generateDailyTrend(303, 1980, 5100, 64, 1.5),
    revenueBreakdown: [
      { name: "Cookware", value: 22_800, color: "#FF9900" },
      { name: "Knives & Tools", value: 16_420, color: "#232F3E" },
      { name: "Storage & Org", value: 14_290, color: "#146EB4" },
      { name: "Small Appliances", value: 12_105, color: "#067D62" },
      { name: "Tableware", value: 8_000, color: "#CC0C39" },
    ],
    categoryPerformance: [
      { name: "Pots & Pans", sales: 24_600, fill: "#FF9900" },
      { name: "Cutlery", sales: 16_800, fill: "#232F3E" },
      { name: "Food Storage", sales: 13_400, fill: "#146EB4" },
      { name: "Gadgets", sales: 11_200, fill: "#067D62" },
      { name: "Serveware", sales: 7_615, fill: "#CC0C39" },
    ],
    inventoryAlerts: [
      { id: "kt-a1", product: "Tri-Ply Saucepan 3qt", sku: "CCE-POT-017", message: "Stranded inventory at ONT8 — transfer recommended", severity: "warning" },
      { id: "kt-a2", product: "Chef Knife 8in Damascus", sku: "CCE-KNF-042", message: "Stockout risk in 4 days at current velocity", severity: "critical" },
      { id: "kt-a3", product: "Glass Meal Prep 20pc", sku: "CCE-MLP-088", message: "Competitor price drop detected — review pricing", severity: "info" },
    ],
    lowStock: [
      { id: "kt-l1", product: "Cast Iron Skillet 12in", sku: "CCE-SKL-003", stock: 14, threshold: 45, imageSeed: "kt-cast-iron" },
      { id: "kt-l2", product: "Silicone Utensil Set 12pc", sku: "CCE-UTN-056", stock: 9, threshold: 30, imageSeed: "kt-silicone-utensils" },
      { id: "kt-l3", product: "Electric Kettle 1.7L", sku: "CCE-KTL-021", stock: 6, threshold: 22, imageSeed: "kt-electric-kettle" },
      { id: "kt-l4", product: "Bamboo Cutting Board XL", sku: "CCE-CBD-014", stock: 11, threshold: 28, imageSeed: "kt-bamboo-board" },
    ],
    recentOrders: [
      { id: "kt-o1", orderNumber: "113-7721045", customer: "Robert C.", product: "Non-Stick Fry Pan 10in", amount: 34.99, status: "shipped", timeAgo: "15 min ago", imageSeed: "kt-fry-pan" },
      { id: "kt-o2", orderNumber: "113-7720987", customer: "Lisa F.", product: "Stand Mixer Attachments 5pc", amount: 49.95, status: "pending", timeAgo: "32 min ago", imageSeed: "kt-mixer-attach" },
      { id: "kt-o3", orderNumber: "113-7720912", customer: "Tom G.", product: "Chef Knife 8in Damascus", amount: 79.0, status: "delivered", timeAgo: "58 min ago", imageSeed: "kt-chef-knife" },
      { id: "kt-o4", orderNumber: "113-7720845", customer: "Karen D.", product: "Spice Rack Organizer", amount: 27.5, status: "shipped", timeAgo: "1.5 hr ago", imageSeed: "kt-spice-rack" },
      { id: "kt-o5", orderNumber: "113-7720778", customer: "Mike S.", product: "French Press 34oz", amount: 32.0, status: "pending", timeAgo: "2 hr ago", imageSeed: "kt-french-press" },
    ],
    notifications: [
      { id: "kt-n1", title: "Stranded inventory", message: "18 units of Tri-Ply Saucepan flagged at ONT8", timeAgo: "25 min ago", type: "inventory" },
      { id: "kt-n2", title: "Prime Day prep", message: "Lightning deal slot confirmed for Cast Iron Skillet", timeAgo: "1 hr ago", type: "system" },
      { id: "kt-n3", title: "Order spike", message: "Chef Knife 8in — 47 orders in the last 6 hours", timeAgo: "3 hr ago", type: "order" },
      { id: "kt-n4", title: "Fee preview", message: "February FBA storage fees estimated at $892.14", timeAgo: "6 hr ago", type: "payment" },
    ],
    activityTimeline: [
      { id: "kt-t1", title: "Order confirmed", description: "113-7721045 — Non-Stick Fry Pan expedited shipping selected", timeAgo: "15 min ago", type: "order" },
      { id: "kt-t2", title: "Restock shipped", description: "200x Cast Iron Skillet inbound to FTW1", timeAgo: "2 hr ago", type: "inventory" },
      { id: "kt-t3", title: "A+ Content approved", description: "Electric Kettle 1.7L enhanced brand content live", timeAgo: "4 hr ago", type: "listing" },
      { id: "kt-t4", title: "Customer message", description: "Pre-purchase question answered for Bamboo Cutting Board", timeAgo: "5 hr ago", type: "order" },
      { id: "kt-t5", title: "Coupon created", description: "15% off Silicone Utensil Set — 500 redemptions max", timeAgo: "Yesterday", type: "listing" },
      { id: "kt-t6", title: "Disbursement", description: "$6,142.88 payout deposited successfully", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  electronics: {
    lastUpdated: "Today at 11:03 AM EST",
    kpis: {
      todaysSales: 8_942.0,
      todaysSalesChange: 15.4,
      totalOrders: 1_876,
      totalOrdersChange: 7.6,
      totalRevenue: 312_470.25,
      totalRevenueChange: 18.1,
      pendingOrders: 41,
      returnOrders: 52,
      conversionRate: 2.4,
      conversionRateChange: 0.3,
    },
    dailyTrend: generateDailyTrend(404, 8200, 28500, 58, 3.2),
    revenueBreakdown: [
      { name: "Audio & Headphones", value: 98_400, color: "#146EB4" },
      { name: "Smart Home", value: 76_820, color: "#FF9900" },
      { name: "Computing Accessories", value: 62_150, color: "#232F3E" },
      { name: "Mobile Accessories", value: 48_900, color: "#067D62" },
      { name: "Cables & Power", value: 26_200, color: "#CC0C39" },
    ],
    categoryPerformance: [
      { name: "Wireless Audio", sales: 112_000, fill: "#146EB4" },
      { name: "Smart Devices", sales: 89_400, fill: "#FF9900" },
      { name: "Peripherals", sales: 54_200, fill: "#232F3E" },
      { name: "Charging", sales: 38_870, fill: "#067D62" },
      { name: "Components", sales: 18_000, fill: "#CC0C39" },
    ],
    inventoryAlerts: [
      { id: "el-a1", product: "ANC Wireless Earbuds Pro", sku: "VET-AUD-001", message: "Firmware recall notice — batch VE-2024-Q3 affected", severity: "critical" },
      { id: "el-a2", product: "USB-C Hub 7-in-1", sku: "VET-HUB-044", message: "Competing listing undercutting by $4.99", severity: "warning" },
      { id: "el-a3", product: "Smart Plug 4-Pack", sku: "VET-SMT-012", message: "Prime badge eligibility restored", severity: "info" },
    ],
    lowStock: [
      { id: "el-l1", product: "Mechanical Keyboard RGB", sku: "VET-KBD-018", stock: 3, threshold: 15, imageSeed: "el-mechanical-kb" },
      { id: "el-l2", product: "Portable SSD 1TB", sku: "VET-SSD-007", stock: 8, threshold: 25, imageSeed: "el-portable-ssd" },
      { id: "el-l3", product: "Webcam 4K Pro", sku: "VET-CAM-003", stock: 5, threshold: 20, imageSeed: "el-webcam-4k" },
      { id: "el-l4", product: "GaN Charger 65W", sku: "VET-CHG-029", stock: 10, threshold: 35, imageSeed: "el-gan-charger" },
    ],
    recentOrders: [
      { id: "el-o1", orderNumber: "111-9921044", customer: "Alex J.", product: "ANC Wireless Earbuds Pro", amount: 149.99, status: "shipped", timeAgo: "6 min ago", imageSeed: "el-earbuds-pro" },
      { id: "el-o2", orderNumber: "111-9920988", customer: "Sam R.", product: "Smart Doorbell Camera", amount: 189.0, status: "pending", timeAgo: "19 min ago", imageSeed: "el-doorbell-cam" },
      { id: "el-o3", orderNumber: "111-9920912", customer: "Jordan P.", product: "Portable SSD 1TB", amount: 119.99, status: "delivered", timeAgo: "40 min ago", imageSeed: "el-ssd-order" },
      { id: "el-o4", orderNumber: "111-9920845", customer: "Taylor M.", product: "USB-C Hub 7-in-1", amount: 42.99, status: "shipped", timeAgo: "1 hr ago", imageSeed: "el-usbc-hub" },
      { id: "el-o5", orderNumber: "111-9920778", customer: "Casey L.", product: "Mechanical Keyboard RGB", amount: 89.99, status: "returned", timeAgo: "2 hr ago", imageSeed: "el-kb-return" },
    ],
    notifications: [
      { id: "el-n1", title: "Recall advisory", message: "Review affected ANC Earbuds batch VE-2024-Q3 immediately", timeAgo: "30 min ago", type: "system" },
      { id: "el-n2", title: "High-value order", message: "Order 111-9920988 — Smart Doorbell Camera ($189.00)", timeAgo: "19 min ago", type: "order" },
      { id: "el-n3", title: "Account health", message: "Order defect rate improved to 0.4% — Good standing", timeAgo: "2 hr ago", type: "system" },
      { id: "el-n4", title: "Reserve released", message: "$24,800 reserve balance released to available funds", timeAgo: "Yesterday", type: "payment" },
    ],
    activityTimeline: [
      { id: "el-t1", title: "Express shipment", description: "111-9921044 — ANC Earbuds shipped same-day from BWI2", timeAgo: "6 min ago", type: "order" },
      { id: "el-t2", title: "Return received", description: "Mechanical Keyboard RGB — defective key reported", timeAgo: "2 hr ago", type: "return" },
      { id: "el-t3", title: "Price automation", description: "GaN Charger 65W repriced to match Buy Box at $29.99", timeAgo: "3 hr ago", type: "listing" },
      { id: "el-t4", title: "Inbound checked in", description: "500 units Webcam 4K Pro received at LAX9", timeAgo: "5 hr ago", type: "inventory" },
      { id: "el-t5", title: "Vine review", description: "Smart Plug 4-Pack received 4.8★ Vine review", timeAgo: "Yesterday", type: "listing" },
      { id: "el-t6", title: "Large disbursement", description: "$28,412.50 standard payout processed", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  beauty: {
    lastUpdated: "Today at 9:18 AM EST",
    kpis: {
      todaysSales: 3_124.85,
      todaysSalesChange: 9.2,
      totalOrders: 4_823,
      totalOrdersChange: 11.4,
      totalRevenue: 89_342.64,
      totalRevenueChange: 10.7,
      pendingOrders: 167,
      returnOrders: 42,
      conversionRate: 5.8,
      conversionRateChange: 0.8,
    },
    dailyTrend: generateDailyTrend(505, 2640, 4200, 142, 1.8),
    revenueBreakdown: [
      { name: "Skincare", value: 38_920, color: "#CC0C39" },
      { name: "Hair Care", value: 22_140, color: "#FF9900" },
      { name: "Makeup", value: 15_680, color: "#232F3E" },
      { name: "Fragrance", value: 8_902, color: "#146EB4" },
      { name: "Tools & Devices", value: 3_700, color: "#067D62" },
    ],
    categoryPerformance: [
      { name: "Serums & Treatments", sales: 28_400, fill: "#CC0C39" },
      { name: "Cleansers", sales: 18_900, fill: "#FF9900" },
      { name: "Moisturizers", sales: 16_200, fill: "#232F3E" },
      { name: "Shampoo & Conditioner", sales: 14_800, fill: "#146EB4" },
      { name: "Lip & Eye", sales: 11_042, fill: "#067D62" },
    ],
    inventoryAlerts: [
      { id: "bt-a1", product: "Vitamin C Serum 30ml", sku: "GTB-SRM-001", message: "Expiration within 90 days — 840 units affected", severity: "critical" },
      { id: "bt-a2", product: "Hydrating Face Mask 10pk", sku: "GTB-MSK-028", message: "Subscribe & Save enrollment up 340% this week", severity: "info" },
      { id: "bt-a3", product: "Retinol Night Cream", sku: "GTB-CRM-015", message: "Meltable inventory risk — transfer to cooler FC", severity: "warning" },
    ],
    lowStock: [
      { id: "bt-l1", product: "Hyaluronic Acid Toner", sku: "GTB-TNR-008", stock: 18, threshold: 50, imageSeed: "bt-ha-toner" },
      { id: "bt-l2", product: "Argan Oil Hair Serum", sku: "GTB-HRS-022", stock: 7, threshold: 30, imageSeed: "bt-argan-serum" },
      { id: "bt-l3", product: "SPF 50 Sunscreen 3oz", sku: "GTB-SPF-004", stock: 22, threshold: 60, imageSeed: "bt-spf-sunscreen" },
      { id: "bt-l4", product: "Lash Growth Serum", sku: "GTB-LSH-011", stock: 9, threshold: 25, imageSeed: "bt-lash-serum" },
    ],
    recentOrders: [
      { id: "bt-o1", orderNumber: "115-6612044", customer: "Mia K.", product: "Vitamin C Serum 30ml", amount: 24.99, status: "shipped", timeAgo: "5 min ago", imageSeed: "bt-vitc-order" },
      { id: "bt-o2", orderNumber: "115-6611988", customer: "Sophia L.", product: "Hydrating Face Mask 10pk", amount: 18.95, status: "pending", timeAgo: "14 min ago", imageSeed: "bt-mask-order" },
      { id: "bt-o3", orderNumber: "115-6611922", customer: "Ava M.", product: "Retinol Night Cream", amount: 32.0, status: "delivered", timeAgo: "38 min ago", imageSeed: "bt-retinol-order" },
      { id: "bt-o4", orderNumber: "115-6611855", customer: "Isabella R.", product: "Matte Lipstick Set 6pc", amount: 29.99, status: "shipped", timeAgo: "52 min ago", imageSeed: "bt-lipstick-order" },
      { id: "bt-o5", orderNumber: "115-6611788", customer: "Chloe T.", product: "Jade Roller & Gua Sha Kit", amount: 21.5, status: "pending", timeAgo: "1 hr ago", imageSeed: "bt-jade-roller" },
    ],
    notifications: [
      { id: "bt-n1", title: "Subscribe & Save", message: "847 new S&S subscriptions for Vitamin C Serum", timeAgo: "20 min ago", type: "order" },
      { id: "bt-n2", title: "Expiration alert", message: "840 units approaching 90-day expiration window", timeAgo: "1 hr ago", type: "inventory" },
      { id: "bt-n3", title: "Coupon redemption", message: "LAUNCH20 coupon — 2,140 redemptions this week", timeAgo: "3 hr ago", type: "system" },
      { id: "bt-n4", title: "Tax document", message: "1099-K preview available for 2025 tax year", timeAgo: "Yesterday", type: "payment" },
    ],
    activityTimeline: [
      { id: "bt-t1", title: "S&S shipment", description: "115-6612044 — Vitamin C Serum auto-ship order fulfilled", timeAgo: "5 min ago", type: "order" },
      { id: "bt-t2", title: "Lot trace", description: "Batch GTB-2025-011 assigned to Hyaluronic Acid Toner", timeAgo: "1 hr ago", type: "inventory" },
      { id: "bt-t3", title: "Listing suppressed", description: "SPF 50 Sunscreen — image compliance issue resolved", timeAgo: "2 hr ago", type: "listing" },
      { id: "bt-t4", title: "Influencer order", description: "15-unit sample order shipped to content creator", timeAgo: "4 hr ago", type: "order" },
      { id: "bt-t5", title: "Review milestone", description: "Argan Oil Hair Serum reached 1,000 reviews at 4.6★", timeAgo: "Yesterday", type: "listing" },
      { id: "bt-t6", title: "Payout", description: "$7,842.33 biweekly disbursement completed", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  toys: {
    lastUpdated: "Today at 10:47 AM EST",
    kpis: {
      todaysSales: 5_678.2,
      todaysSalesChange: 22.1,
      totalOrders: 5_641,
      totalOrdersChange: 18.9,
      totalRevenue: 156_908.33,
      totalRevenueChange: 20.4,
      pendingOrders: 203,
      returnOrders: 67,
      conversionRate: 6.2,
      conversionRateChange: 1.1,
    },
    dailyTrend: generateDailyTrend(606, 4800, 7800, 168, 2.4),
    revenueBreakdown: [
      { name: "Building & STEM", value: 48_200, color: "#146EB4" },
      { name: "Plush & Dolls", value: 34_800, color: "#CC0C39" },
      { name: "Outdoor Play", value: 28_400, color: "#067D62" },
      { name: "Board Games", value: 24_108, color: "#FF9900" },
      { name: "Arts & Crafts", value: 21_400, color: "#232F3E" },
    ],
    categoryPerformance: [
      { name: "STEM Kits", sales: 42_800, fill: "#146EB4" },
      { name: "Action Figures", sales: 31_200, fill: "#CC0C39" },
      { name: "Puzzles", sales: 26_400, fill: "#FF9900" },
      { name: "Outdoor", sales: 28_908, fill: "#067D62" },
      { name: "Educational", sales: 27_600, fill: "#232F3E" },
    ],
    inventoryAlerts: [
      { id: "ty-a1", product: "Magnetic Tile Set 100pc", sku: "WPT-MGT-100", message: "Holiday demand forecast exceeds supply by 2,400 units", severity: "critical" },
      { id: "ty-a2", product: "RC Drone Mini", sku: "WPT-DRN-012", message: "CPSIA compliance documentation due in 14 days", severity: "warning" },
      { id: "ty-a3", product: "Plush Unicorn 18in", sku: "WPT-PLS-044", message: "Trending on Amazon — sales velocity +280%", severity: "info" },
    ],
    lowStock: [
      { id: "ty-l1", product: "LEGO-Compatible Brick Box 500pc", sku: "WPT-BRK-500", stock: 21, threshold: 80, imageSeed: "ty-brick-box" },
      { id: "ty-l2", product: "Wooden Train Set 32pc", sku: "WPT-TRN-032", stock: 8, threshold: 35, imageSeed: "ty-train-set" },
      { id: "ty-l3", product: "Slime Making Kit Deluxe", sku: "WPT-SLM-018", stock: 15, threshold: 45, imageSeed: "ty-slime-kit" },
      { id: "ty-l4", product: "Nerf Blaster Twin Pack", sku: "WPT-NRF-006", stock: 6, threshold: 30, imageSeed: "ty-nerf-blaster" },
    ],
    recentOrders: [
      { id: "ty-o1", orderNumber: "116-5512044", customer: "Jennifer A.", product: "Magnetic Tile Set 100pc", amount: 54.99, status: "shipped", timeAgo: "4 min ago", imageSeed: "ty-magnetic-tiles" },
      { id: "ty-o2", orderNumber: "116-5511988", customer: "Brian H.", product: "RC Drone Mini", amount: 39.95, status: "pending", timeAgo: "11 min ago", imageSeed: "ty-rc-drone" },
      { id: "ty-o3", orderNumber: "116-5511922", customer: "Amanda C.", product: "Plush Unicorn 18in", amount: 22.99, status: "delivered", timeAgo: "25 min ago", imageSeed: "ty-plush-unicorn" },
      { id: "ty-o4", orderNumber: "116-5511855", customer: "Kevin W.", product: "Board Game Strategy Set", amount: 34.0, status: "shipped", timeAgo: "48 min ago", imageSeed: "ty-board-game" },
      { id: "ty-o5", orderNumber: "116-5511788", customer: "Rachel P.", product: "Art Supply Kit 120pc", amount: 28.5, status: "pending", timeAgo: "1 hr ago", imageSeed: "ty-art-kit" },
    ],
    notifications: [
      { id: "ty-n1", title: "Velocity alert", message: "Magnetic Tile Set selling 12 units/hour — restock urgently", timeAgo: "8 min ago", type: "inventory" },
      { id: "ty-n2", title: "Gift wrap surge", message: "Gift wrap option selected on 34% of orders today", timeAgo: "45 min ago", type: "order" },
      { id: "ty-n3", title: "Deal of the Day", message: "Plush Unicorn featured — expect 3x traffic", timeAgo: "2 hr ago", type: "system" },
      { id: "ty-n4", title: "Reserve hold", message: "$8,420 held in holiday reserve — releases Mar 1", timeAgo: "Yesterday", type: "payment" },
    ],
    activityTimeline: [
      { id: "ty-t1", title: "Gift order", description: "116-5512044 — Magnetic Tiles with gift message included", timeAgo: "4 min ago", type: "order" },
      { id: "ty-t2", title: "Inbound priority", description: "Emergency shipment 2,000 Magnetic Tiles en route to MDW2", timeAgo: "1 hr ago", type: "inventory" },
      { id: "ty-t3", title: "Safety cert uploaded", description: "RC Drone Mini CPSIA test report submitted", timeAgo: "3 hr ago", type: "listing" },
      { id: "ty-t4", title: "Multi-unit order", description: "116-5511855 — Board Game x4 units to single address", timeAgo: "48 min ago", type: "order" },
      { id: "ty-t5", title: "Parent review", description: "Wooden Train Set — verified purchase 5★ review posted", timeAgo: "Yesterday", type: "listing" },
      { id: "ty-t6", title: "Payout", description: "$14,218.67 disbursement deposited", timeAgo: "Yesterday", type: "payment" },
    ],
  },

  jewellery: {
    lastUpdated: "Today at 9:55 AM EST",
    kpis: {
      todaysSales: 2_890.45,
      todaysSalesChange: 4.8,
      totalOrders: 892,
      totalOrdersChange: 3.1,
      totalRevenue: 64_175.4,
      totalRevenueChange: 6.5,
      pendingOrders: 19,
      returnOrders: 24,
      conversionRate: 1.9,
      conversionRateChange: -0.1,
    },
    dailyTrend: generateDailyTrend(707, 1850, 4800, 28, 1.0),
    revenueBreakdown: [
      { name: "Rings", value: 22_400, color: "#FF9900" },
      { name: "Necklaces", value: 18_920, color: "#CC0C39" },
      { name: "Earrings", value: 12_650, color: "#146EB4" },
      { name: "Bracelets", value: 7_805, color: "#067D62" },
      { name: "Watches", value: 2_400, color: "#232F3E" },
    ],
    categoryPerformance: [
      { name: "Sterling Silver", sales: 24_800, fill: "#FF9900" },
      { name: "Gold Plated", sales: 18_200, fill: "#CC0C39" },
      { name: "Gemstone", sales: 12_400, fill: "#146EB4" },
      { name: "Pearl", sales: 5_775, fill: "#067D62" },
      { name: "Fashion", sales: 3_000, fill: "#232F3E" },
    ],
    inventoryAlerts: [
      { id: "jw-a1", product: "14K Gold Hoop Earrings", sku: "LMJ-EAR-014", message: "High-value item — only 2 units in FBA", severity: "critical" },
      { id: "jw-a2", product: "Sapphire Pendant Necklace", sku: "LMJ-NCK-028", message: "Certificate of authenticity missing for 3 units", severity: "warning" },
      { id: "jw-a3", product: "Tennis Bracelet CZ", sku: "LMJ-BRC-011", message: "Valentine's Day campaign performing above target", severity: "info" },
    ],
    lowStock: [
      { id: "jw-l1", product: "Diamond Stud Earrings 1ct", sku: "LMJ-EAR-001", stock: 2, threshold: 8, imageSeed: "jw-diamond-studs" },
      { id: "jw-l2", product: "Rose Gold Band Ring Size 7", sku: "LMJ-RNG-042", stock: 4, threshold: 12, imageSeed: "jw-rose-ring" },
      { id: "jw-l3", product: "Pearl Strand Necklace 18in", sku: "LMJ-NCK-008", stock: 3, threshold: 10, imageSeed: "jw-pearl-necklace" },
      { id: "jw-l4", product: "Charm Bracelet Silver", sku: "LMJ-BRC-019", stock: 6, threshold: 15, imageSeed: "jw-charm-bracelet" },
    ],
    recentOrders: [
      { id: "jw-o1", orderNumber: "117-3312044", customer: "Victoria S.", product: "14K Gold Hoop Earrings", amount: 189.0, status: "shipped", timeAgo: "20 min ago", imageSeed: "jw-gold-hoops" },
      { id: "jw-o2", orderNumber: "117-3311988", customer: "Daniel M.", product: "Sapphire Pendant Necklace", amount: 245.0, status: "pending", timeAgo: "42 min ago", imageSeed: "jw-sapphire-pendant" },
      { id: "jw-o3", orderNumber: "117-3311922", customer: "Grace H.", product: "Diamond Stud Earrings 1ct", amount: 599.99, status: "delivered", timeAgo: "1 hr ago", imageSeed: "jw-diamond-order" },
      { id: "jw-o4", orderNumber: "117-3311855", customer: "Ethan B.", product: "Tennis Bracelet CZ", amount: 78.0, status: "shipped", timeAgo: "2 hr ago", imageSeed: "jw-tennis-bracelet" },
      { id: "jw-o5", orderNumber: "117-3311788", customer: "Hannah L.", product: "Rose Gold Band Ring", amount: 124.5, status: "returned", timeAgo: "4 hr ago", imageSeed: "jw-ring-return" },
    ],
    notifications: [
      { id: "jw-n1", title: "High-value order", message: "Diamond Stud Earrings 1ct — $599.99 order requires signature", timeAgo: "1 hr ago", type: "order" },
      { id: "jw-n2", title: "Authentication", message: "Upload COA for Sapphire Pendant batch LMJ-2025-028", timeAgo: "3 hr ago", type: "inventory" },
      { id: "jw-n3", title: "Gift packaging", message: "Premium gift box option added to 12 listings", timeAgo: "5 hr ago", type: "system" },
      { id: "jw-n4", title: "Insurance claim", message: "Lost shipment claim approved — $245.00 credited", timeAgo: "Yesterday", type: "payment" },
    ],
    activityTimeline: [
      { id: "jw-t1", title: "Signature delivery", description: "117-3311922 — Diamond Studs out for signature delivery", timeAgo: "1 hr ago", type: "order" },
      { id: "jw-t2", title: "Return inspection", description: "Rose Gold Band Ring — sizing return received at FC", timeAgo: "4 hr ago", type: "return" },
      { id: "jw-t3", title: "Listing enhanced", description: "Sapphire Pendant — 360° video uploaded to listing", timeAgo: "6 hr ago", type: "listing" },
      { id: "jw-t4", title: "Secure storage", description: "High-value inventory transferred to secure cage at JFK8", timeAgo: "Yesterday", type: "inventory" },
      { id: "jw-t5", title: "Campaign ROI", description: "Valentine's Sponsored Brands — 4.2x ROAS achieved", timeAgo: "Yesterday", type: "listing" },
      { id: "jw-t6", title: "Payout", description: "$5,842.18 disbursement completed", timeAgo: "2 days ago", type: "payment" },
    ],
  },

  sports: {
    lastUpdated: "Today at 11:22 AM EST",
    kpis: {
      todaysSales: 4_512.9,
      todaysSalesChange: 11.8,
      totalOrders: 2_987,
      totalOrdersChange: 8.4,
      totalRevenue: 198_563.78,
      totalRevenueChange: 13.6,
      pendingOrders: 76,
      returnOrders: 48,
      conversionRate: 3.9,
      conversionRateChange: 0.5,
    },
    dailyTrend: generateDailyTrend(808, 5200, 9800, 88, 2.0),
    revenueBreakdown: [
      { name: "Fitness Equipment", value: 62_400, color: "#067D62" },
      { name: "Team Sports", value: 48_200, color: "#146EB4" },
      { name: "Outdoor Recreation", value: 38_963, color: "#FF9900" },
      { name: "Apparel & Footwear", value: 32_800, color: "#232F3E" },
      { name: "Nutrition", value: 16_200, color: "#CC0C39" },
    ],
    categoryPerformance: [
      { name: "Strength Training", sales: 58_400, fill: "#067D62" },
      { name: "Cardio", sales: 42_800, fill: "#146EB4" },
      { name: "Camping & Hiking", sales: 38_200, fill: "#FF9900" },
      { name: "Cycling", sales: 31_163, fill: "#232F3E" },
      { name: "Yoga & Recovery", sales: 28_000, fill: "#CC0C39" },
    ],
    inventoryAlerts: [
      { id: "sp-a1", product: "Adjustable Dumbbell Set 50lb", sku: "PFS-DMB-050", message: "Oversized item — storage fees increased 18%", severity: "warning" },
      { id: "sp-a2", product: "Carbon Fiber Pickleball Paddle", sku: "PFS-PKL-003", message: "Stockout in 6 days at current sell-through", severity: "critical" },
      { id: "sp-a3", product: "Insulated Hydration Pack 2L", sku: "PFS-HYD-012", message: "Spring season forecast recommends +40% inventory", severity: "info" },
    ],
    lowStock: [
      { id: "sp-l1", product: "Resistance Band Set Pro", sku: "PFS-BND-024", stock: 16, threshold: 50, imageSeed: "sp-resistance-bands" },
      { id: "sp-l2", product: "Yoga Mat 6mm Extra Thick", sku: "PFS-YGM-008", stock: 11, threshold: 40, imageSeed: "sp-yoga-mat" },
      { id: "sp-l3", product: "Running Belt with Bottles", sku: "PFS-RNB-015", stock: 7, threshold: 28, imageSeed: "sp-running-belt" },
      { id: "sp-l4", product: "Camping Lantern LED Rechargeable", sku: "PFS-LNT-006", stock: 9, threshold: 32, imageSeed: "sp-camping-lantern" },
    ],
    recentOrders: [
      { id: "sp-o1", orderNumber: "118-2212044", customer: "Ryan D.", product: "Adjustable Dumbbell Set 50lb", amount: 249.99, status: "shipped", timeAgo: "9 min ago", imageSeed: "sp-dumbbell-set" },
      { id: "sp-o2", orderNumber: "118-2211988", customer: "Michelle F.", product: "Carbon Fiber Pickleball Paddle", amount: 89.95, status: "pending", timeAgo: "24 min ago", imageSeed: "sp-pickleball" },
      { id: "sp-o3", orderNumber: "118-2211922", customer: "Jason K.", product: "Insulated Hydration Pack 2L", amount: 54.0, status: "delivered", timeAgo: "55 min ago", imageSeed: "sp-hydration-pack" },
      { id: "sp-o4", orderNumber: "118-2211855", customer: "Lauren T.", product: "Foam Roller High Density", amount: 32.99, status: "shipped", timeAgo: "1.5 hr ago", imageSeed: "sp-foam-roller" },
      { id: "sp-o5", orderNumber: "118-2211788", customer: "Eric M.", product: "Basketball Official Size 7", amount: 28.5, status: "pending", timeAgo: "2 hr ago", imageSeed: "sp-basketball" },
    ],
    notifications: [
      { id: "sp-n1", title: "Oversized fee", message: "Adjustable Dumbbell Set — monthly storage fee $42.18", timeAgo: "1 hr ago", type: "inventory" },
      { id: "sp-n2", title: "Team order", message: "118-2211788 — 12x Basketball to youth league address", timeAgo: "2 hr ago", type: "order" },
      { id: "sp-n3", title: "Seasonal forecast", message: "Spring outdoor category projected +35% demand", timeAgo: "4 hr ago", type: "system" },
      { id: "sp-n4", title: "Payout", message: "$9,842.56 standard disbursement scheduled", timeAgo: "Yesterday", type: "payment" },
    ],
    activityTimeline: [
      { id: "sp-t1", title: "Freight shipment", description: "118-2212044 — Dumbbell set shipped LTL freight", timeAgo: "9 min ago", type: "order" },
      { id: "sp-t2", title: "Restock order", description: "500x Pickleball Paddle PO sent to manufacturer", timeAgo: "2 hr ago", type: "inventory" },
      { id: "sp-t3", title: "Deal enrollment", description: "Yoga Mat enrolled in Spring Fitness promotion", timeAgo: "4 hr ago", type: "listing" },
      { id: "sp-t4", title: "A-to-z claim", description: "Foam Roller claim denied — tracking confirmed delivery", timeAgo: "6 hr ago", type: "return" },
      { id: "sp-t5", title: "Brand analytics", description: "PeakForge Sports search rank improved 12 positions", timeAgo: "Yesterday", type: "listing" },
      { id: "sp-t6", title: "Disbursement", description: "$9,842.56 deposited to bank account", timeAgo: "Yesterday", type: "payment" },
    ],
  },
};

export function getDashboardData(categoryId: string) {
  const id = categoryId as keyof DashboardDataMap;
  return dashboardDataByCategory[id] ?? dashboardDataByCategory["home-decor"];
}
