import { encodeProductPublicPath } from "@/lib/demo/products/get-product-image";
import { getSellerAccount } from "@/lib/demo/seller-accounts";
import type { DemoProduct } from "@/types/product";
import type { InventoryStatus } from "@/types/inventory";
import type { SellerCategoryId } from "@/types/seller";

type CatalogSeed = {
  id: string;
  name: string;
  sku: string;
  asin: string;
  categoryId: SellerCategoryId;
  folder: string;
  file: string;
  description: string;
  stock: number;
  reserved: number;
  warehouse: string;
  price: number;
  status: InventoryStatus;
  fulfillment: "FBA" | "FBM";
  lastUpdated: string;
};

const CATALOG_SEEDS: CatalogSeed[] = [
  {
    id: "prod-bp-001",
    name: "TELGO Travel Backpack — Sky Blue",
    sku: "TELGO-BP-001",
    asin: "B089N6F2C9",
    categoryId: "fashion",
    folder: "Bag Pack",
    file: "Bagpack.jpg.jfif",
    description: "Unisex laptop travel backpack with padded compartment and USB charging port.",
    stock: 142,
    reserved: 18,
    warehouse: "PHX7",
    price: 999,
    status: "in_stock",
    fulfillment: "FBM",
    lastUpdated: "2 hr ago",
  },
  {
    id: "prod-bp-002",
    name: "TELGO Laptop Backpack — Charcoal",
    sku: "TELGO-BP-002",
    asin: "B089N6F2D0",
    categoryId: "fashion",
    folder: "Bag Pack",
    file: "Bagpack.jpg (2).jfif",
    description: "Anti-theft business backpack with 15.6in laptop sleeve and water-resistant fabric.",
    stock: 87,
    reserved: 12,
    warehouse: "EWR4",
    price: 1099,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "45 min ago",
  },
  {
    id: "prod-bp-003",
    name: "TELGO Daypack — Olive Green",
    sku: "TELGO-BP-003",
    asin: "B089N6F2E7",
    categoryId: "sports",
    folder: "Bag Pack",
    file: "Bagpack.jpg (3).jfif",
    description: "Lightweight daypack for hiking and daily commute with ventilated back panel.",
    stock: 28,
    reserved: 4,
    warehouse: "ONT8",
    price: 849,
    status: "low_stock",
    fulfillment: "FBA",
    lastUpdated: "1 hr ago",
  },
  {
    id: "prod-bp-004",
    name: "TELGO Weekender Bag — Black",
    sku: "TELGO-BP-004",
    asin: "B089N6F2F4",
    categoryId: "fashion",
    folder: "Bag Pack",
    file: "Bagpack.jpg (4).jfif",
    description: "Expandable weekender with shoe compartment and trolley sleeve.",
    stock: 64,
    reserved: 9,
    warehouse: "FTW1",
    price: 1299,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "3 hr ago",
  },
  {
    id: "prod-bp-005",
    name: "TELGO Anti-Theft Backpack — Navy",
    sku: "TELGO-BP-005",
    asin: "B089N6F2G1",
    categoryId: "electronics",
    folder: "Bag Pack",
    file: "Bagpack.jpg (5).jfif",
    description: "Secure travel backpack with hidden zippers and RFID-blocking pocket.",
    stock: 10,
    reserved: 3,
    warehouse: "BWI2",
    price: 1199,
    status: "low_stock",
    fulfillment: "FBM",
    lastUpdated: "20 min ago",
  },
  {
    id: "prod-bp-006",
    name: "TELGO USB Charging Backpack — Grey",
    sku: "TELGO-BP-006",
    asin: "B089N6F2H8",
    categoryId: "electronics",
    folder: "Bag Pack",
    file: "Bagpack.jpg (6).jfif",
    description: "Smart backpack with built-in USB port and multiple organizer pockets.",
    stock: 0,
    reserved: 0,
    warehouse: "LAX9",
    price: 949,
    status: "out_of_stock",
    fulfillment: "FBA",
    lastUpdated: "6 hr ago",
  },
  {
    id: "prod-hb-001",
    name: "Classic Leather Handbag — Tan",
    sku: "HDB-HB-001",
    asin: "B08FASH101",
    categoryId: "fashion",
    folder: "Hand Bag",
    file: "Hand Bag.jpg.png",
    description: "Genuine leather top-handle handbag with detachable crossbody strap.",
    stock: 56,
    reserved: 8,
    warehouse: "MDW2",
    price: 2499,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "55 min ago",
  },
  {
    id: "prod-hb-002",
    name: "Crossbody Satchel — Burgundy",
    sku: "HDB-HB-002",
    asin: "B08FASH102",
    categoryId: "fashion",
    folder: "Hand Bag",
    file: "Hand Bag 2.jpg.png",
    description: "Compact crossbody satchel with magnetic closure and interior zip pocket.",
    stock: 18,
    reserved: 6,
    warehouse: "JFK8",
    price: 1899,
    status: "low_stock",
    fulfillment: "FBA",
    lastUpdated: "1.5 hr ago",
  },
  {
    id: "prod-hb-003",
    name: "Structured Tote Bag — Black",
    sku: "HDB-HB-003",
    asin: "B08FASH103",
    categoryId: "fashion",
    folder: "Hand Bag",
    file: "Hand Bag3.jpg.png",
    description: "Professional structured tote with laptop sleeve and gold-tone hardware.",
    stock: 73,
    reserved: 11,
    warehouse: "ATL6",
    price: 2199,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "4 hr ago",
  },
  {
    id: "prod-hb-004",
    name: "Chain Strap Evening Bag — Gold",
    sku: "HDB-HB-004",
    asin: "B08FASH104",
    categoryId: "fashion",
    folder: "Hand Bag",
    file: "Hand Bag4.jpg.png",
    description: "Evening clutch with chain strap and satin-lined interior.",
    stock: 0,
    reserved: 0,
    warehouse: "DEN2",
    price: 1599,
    status: "inbound",
    fulfillment: "FBA",
    lastUpdated: "30 min ago",
  },
  {
    id: "prod-hd-001",
    name: "Modern Home Decor Set",
    sku: "NNH-HD-001",
    asin: "B09HDEC001",
    categoryId: "home-decor",
    folder: "home decor",
    file: "home decor.jpg.jpg",
    description: "Curated tabletop decor set with neutral tones for living spaces.",
    stock: 94,
    reserved: 14,
    warehouse: "PHX7",
    price: 1299,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "2 hr ago",
  },
  {
    id: "prod-hd-002",
    name: "Minimalist Shelf Decor Kit",
    sku: "NNH-HD-002",
    asin: "B09HDEC002",
    categoryId: "home-decor",
    folder: "home decor",
    file: "Homedecor.jpg.jpg",
    description: "Three-piece shelf styling kit with ceramic and wood accents.",
    stock: 38,
    reserved: 12,
    warehouse: "EWR4",
    price: 899,
    status: "low_stock",
    fulfillment: "FBA",
    lastUpdated: "45 min ago",
  },
  {
    id: "prod-hd-003",
    name: "Ceramic Table Lamp — Sage",
    sku: "NNH-LMP-042",
    asin: "B09HDEC003",
    categoryId: "home-decor",
    folder: "home decor",
    file: "Lamp.jpg.jpg",
    description: "Hand-glazed ceramic lamp base with linen drum shade.",
    stock: 142,
    reserved: 18,
    warehouse: "PHX7",
    price: 5499,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "2 hr ago",
  },
  {
    id: "prod-hd-004",
    name: "Ceramic Vase Set of 3",
    sku: "NNH-VAS-091",
    asin: "B09HDEC004",
    categoryId: "home-decor",
    folder: "home decor",
    file: "Vases.jpg.jpg",
    description: "Matte finish ceramic vases in graduated sizes for floral arrangements.",
    stock: 5,
    reserved: 2,
    warehouse: "ONT8",
    price: 6250,
    status: "low_stock",
    fulfillment: "FBA",
    lastUpdated: "2 hr ago",
  },
  {
    id: "prod-jw-001",
    name: "Sterling Silver Pendant Necklace",
    sku: "LJ-NK-113",
    asin: "B09JEWL113",
    categoryId: "jewellery",
    folder: "Jewellery",
    file: "LJ113.jpg.jpg",
    description: "925 sterling silver pendant on adjustable chain with gift box.",
    stock: 210,
    reserved: 31,
    warehouse: "BWI2",
    price: 1899,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "55 min ago",
  },
  {
    id: "prod-jw-002",
    name: "Gold-Plated Hoop Earrings",
    sku: "LJ-ER-114",
    asin: "B09JEWL114",
    categoryId: "jewellery",
    folder: "Jewellery",
    file: "LJ114.jpg.jpg",
    description: "18K gold-plated hoops with secure click-top closure.",
    stock: 156,
    reserved: 22,
    warehouse: "FTW1",
    price: 999,
    status: "in_stock",
    fulfillment: "FBA",
    lastUpdated: "20 min ago",
  },
  {
    id: "prod-jw-003",
    name: "Crystal Drop Earrings Set",
    sku: "LJ-ER-068",
    asin: "B09JEWL068",
    categoryId: "jewellery",
    folder: "Jewellery",
    file: "LJ68.jpg.jpg",
    description: "Faceted crystal drop earrings for formal occasions.",
    stock: 12,
    reserved: 8,
    warehouse: "EWR4",
    price: 1499,
    status: "low_stock",
    fulfillment: "FBA",
    lastUpdated: "1 hr ago",
  },
  {
    id: "prod-jw-004",
    name: "Layered Chain Bracelet",
    sku: "LJ-BR-072",
    asin: "B09JEWL072",
    categoryId: "jewellery",
    folder: "Jewellery",
    file: "LJ72.jpg.jpg",
    description: "Three-layer chain bracelet with lobster clasp and extender.",
    stock: 0,
    reserved: 0,
    warehouse: "PHX7",
    price: 1299,
    status: "stranded",
    fulfillment: "FBA",
    lastUpdated: "Yesterday",
  },
];

function toProduct(seed: CatalogSeed): DemoProduct {
  const account = getSellerAccount(seed.categoryId);
  return {
    id: seed.id,
    name: seed.name,
    sku: seed.sku,
    asin: seed.asin,
    categoryId: seed.categoryId,
    categoryLabel: account.categoryLabel,
    imageFolder: seed.folder,
    imageFile: seed.file,
    imageUrl: encodeProductPublicPath(seed.folder, seed.file),
    imageSeed: seed.id,
    description: seed.description,
    stock: seed.stock,
    reserved: seed.reserved,
    available: Math.max(0, seed.stock - seed.reserved),
    warehouse: seed.warehouse,
    price: seed.price,
    status: seed.status,
    listingStatus: seed.status === "stranded" ? "Inactive" : "Active",
    fulfillment: seed.fulfillment,
    lastUpdated: seed.lastUpdated,
  };
}

export const UPLOADED_PRODUCT_CATALOG: DemoProduct[] = CATALOG_SEEDS.map(toProduct);

export function getCatalogProductById(id: string): DemoProduct | undefined {
  return UPLOADED_PRODUCT_CATALOG.find((product) => product.id === id);
}

export function getCatalogProductBySku(sku: string): DemoProduct | undefined {
  return UPLOADED_PRODUCT_CATALOG.find((product) => product.sku === sku);
}
