/** Auto-generated by scripts/sync-product-images.mjs — do not edit manually */
export const PRODUCT_IMAGE_FOLDERS = {
  "Bag Pack": [
    "Bagpack.jpg (2).jfif",
    "Bagpack.jpg (3).jfif",
    "Bagpack.jpg (4).jfif",
    "Bagpack.jpg (5).jfif",
    "Bagpack.jpg (6).jfif",
    "Bagpack.jpg.jfif"
  ],
  "Hand Bag": [
    "Hand Bag 2.jpg.png",
    "Hand Bag.jpg.png",
    "Hand Bag3.jpg.png",
    "Hand Bag4.jpg.png"
  ],
  "home decor": [
    "home decor.jpg.jpg",
    "Homedecor.jpg.jpg",
    "Lamp.jpg.jpg",
    "Vases.jpg.jpg"
  ],
  "Jewellery": [
    "LJ113.jpg.jpg",
    "LJ114.jpg.jpg",
    "LJ68.jpg.jpg",
    "LJ72.jpg.jpg"
  ]
} as const;

export type ProductImageFolder = keyof typeof PRODUCT_IMAGE_FOLDERS;
